// +---------------- DO NO EDIT ! ---------------- +
// |      This file was generated by sqrible       |
// +---------------------------------------------- +

package {% block pkgname %}{{ Table.GoStructName | lower }}{% endblock %}

{% block imports %}{% endblock %}

var ErrNotFound = errors.New("row not found in {{ Table.Name }}")

{% block struct %}
    {% include "helpers/funcs/struct.tpl" %}
{% endblock %}

{% block func_tablename %}
    {% include "helpers/funcs/tablename.tpl" %}
{% endblock %}

{% block func_structscan %}
    {% include "helpers/funcs/structscan.tpl" %}
{% endblock %}

{% block func_structscanrows %}
    {% include "helpers/funcs/structscanrows.tpl" %}
{% endblock %}

{% block func_insert %}
    {% if Table.InsertableColumns | length > 0 %}
        {% include "helpers/funcs/insert.tpl" %}
    {% endif %}
{% endblock %}

{% block func_update %}
    {% if Table.UpdateableColumns | length > 0 %}
        {% include "helpers/funcs/update.tpl" %}
    {% endif %}
{% endblock %}

{% block func_count %}
    {% include "helpers/funcs/count.tpl" %}
{% endblock %}

{% block func_fetchone %}
    {% include "helpers/funcs/fetchone.tpl" %}
{% endblock %}

{% block func_fetchonewithsql %}
    {% include "helpers/funcs/fetchonewithsql.tpl" %}
{% endblock %}

{% block extra %}{% endblock %}
